### ISSUE TITLE
Possibility to choose transition storage class for logs

### ISSUE THREAD

**Issue by chinskiy** [avantoss/vault-infra#31]
Greetings!

Mostly because of cost considerations, I'm interested in the possibility of deciding on the log transition storage class [here](https://github.com/avantoss/vault-infra/blob/fd40533b2bc3127a330d70967ca5a3e433dc6288/terraform/modules/vault/s3.tf#L29) or, probably, I miss something while configuring it.

In my case, CloudWatch shows that on approximately 140 Mb of stored logs, Glacier generates approximately 7.5 Gb of storage overhead charges (6.5 Gb of `GlacierObjectOverhead` + 1.5 `GlacierS3ObjectOverhead`) because of the small log files size inside. 

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html

* `GlacierObjectOverhead` - For each archived object, GLACIER adds 32 KB of storage for index and related metadata. This extra data is necessary to identify and restore your object. You are charged GLACIER rates for this additional storage.

* `GlacierS3ObjectOverhead` - For each object archived to GLACIER, Amazon S3 uses 8 KB of storage for the name of the object and other metadata. You are charged STANDARD rates for this additional storage.

Regards

**Comment by lingrino** [comment]
👋 @chinskiy

This is a great suggestion. Like you mentioned it doesn't even make sense to archive logs since glacier metadata charges are higher than keeping them in standard S3.

We should just delete that block completely, I don't think it's helping anyone. Feel free to submit a PR to [remove the glacier transition](https://github.com/avantoss/vault-infra/blob/fd40533b2bc3127a330d70967ca5a3e433dc6288/terraform/modules/vault/s3.tf#L27-L30). Or I will follow up soon and add some configuration myself.
