### ISSUE TITLE
ACM certificate on internal ALB

### ISSUE THREAD

**Issue by nomatterz** [avantoss/vault-infra#33]
First of all great job guys, thank you for this project!

I forked it and modified it a bit. 
One thing confuses me. Maybe I got something wrong but:
Using vault module internal ALB with https listener is created. 
_Public_ ACM certificate is deployed on it. 
As there is `resource "aws_route53_record" "dns_acm_validation"`  i presume that public hosted zone is used here, right? As we're not able pass dns validation with private hosted zone.

**Comment by lingrino** [comment]
Hello @nomatterz!

I'm glad to hear you're using the project. The idea with acm validation is that you can (and should) pass in your own `var.alb_certificate_arn` but if you don't then the module will attempt to create a public certificate for you. That's why we have [`count = var.alb_certificate_arn == "" ? 1 : 0`](https://github.com/avantoss/vault-infra/blob/master/terraform/modules/vault/acm.tf#L5) on every acm resource. So I think you should prefer to create a new internal ACM certificate outside of this module and pass it directly with `var.alb_certificate_arn`. Then you can keep vault private and internal.

**Comment by nomatterz** [comment]
Hi @lingrino !

Thank you for explanation! Yes, this variable makes sense. I got your idea.

Actually personally I did it another way. I added tls certificates creation to the module ( so tf creates self signed CA cert and certificate for ALB signed by this CA). And because certificate intended for ALB is signed by private CA i deploy it on ALB using [aws_iam_server_certificate resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_server_certificate).   
So the idea is - i'm using private certificate for internal ALB and not using AWS Private CA which is quite expensive and is overkill for my use case ( 1 private certificate)
Maybe this approach will be useful for someone else.

Thanks again!
